services:
  c1_spatial:
    image: cefect/usfloods_inference_c1:v0
    volumes:
      - ../..:/workspace:cached
    working_dir: /workspace
    tty: true
    stdin_open: true
    # Overrides default command so things don't shut down after the process ends.
    command: /bin/sh -c "while sleep 1000; do :; done"